1.Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [0, 40]
Compare each element of array1 and array2
Output: [ True False False True False]



In [3]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])

output = np.isin(array2 , array1)

print("Array1:", array1)
print("Array2:", array2)
print("Compare each element of array1 and array2")
print("Output:", output)

Array1: [ 0 10 20 40 60]
Array2: [ 0 40]
Compare each element of array1 and array2
Output: [ True  True]


2.Write a NumPy program to get the unique elements of an array
Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]

In [ ]:
array1= np.array([10, 10, 20, 20, 30, 40, 40])
array2 = np.array([[1, 1],[2, 3]])

#print("")
print("Original array:")
print(array1)

unique_ele = np.unique(array1)

#print()
print("Unique elements of the above array:")
print(unique_ele)

#print original array
print("Original array:")
print(array2)

unique_ele = np.unique(array2)

print("Unique elements of the above array:")

print(unique_ele)



3.Write a NumPy program to sort an along the first, last axis of an array.
Sample array: [[2,5],[4,4]]
Expected Output:
Original array:
[[4 6]
[2 1]]
Sort along the first axis:
[[2 1]
[4 6]]
Sort along the last axis:
[[1 2]
[4 6]]


In [4]:
import numpy as np

# Define the sample array
sample_array = np.array([[4, 6], [2, 1]])

# Print the original array
print("Original array:")
print(sample_array)

# Sort along the first axis
sorted_first_axis = np.sort(sample_array, axis = 0)
#sorted_first_axis = np.sort(sample_array, axis=0)
print("Sort along the first axis:")
print(sorted_first_axis)

# Sort along the last axis
sorted_last_axis = np.sort(sample_array, axis = -1)
#sorted_last_axis = np.sort(sample_array, axis=-1)
print("Sort along the last axis:")
print(sorted_last_axis)


Original array:
[[4 6]
 [2 1]]
Sort along the first axis:
[[2 1]
 [4 6]]
Sort along the last axis:
[[4 6]
 [1 2]]


4.Write a NumPy program to count the occurrence of a specified item in a given NumPy array.
Sample Output:
Original array:
[10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]
[4,1,7,3]


In [7]:
array1 = np.array([0, 20, 30, 30, 30, 0, 0, 20, 20, 0])

specified_item = 4

occurence = np.count_nonzero(array1 == specified_item)

print("Original array:")
print(array1)
print("Occurrences of", specified_item, ":", occurence)

Original array:
[ 0 20 30 30 30  0  0 20 20  0]
Occurrences of 4 : 0


In [10]:
original_array = np.array([[1,2, 3],
                            [4, 5, 6],
                           [ 7 ,8, 9]])

specified_item = 5

boolean_array =  original_array == specified_item

print(boolean_array)
occurence = np.count_nonzero(boolean_array)
print(occurence)

[[False False False]
 [False  True False]
 [False False False]]
1


5.Write a NumPy program to remove nan values from a given array.
Sample Output:
Original array:
[200. 300. nan nan nan 700.]
After removing nan values:
[200. 300. 700.]

In [12]:
import numpy as np

# Define the original array
original_array = np.array([200, 300, np.nan, np.nan, np.nan, 700])

# Print the original array
print("Original array:")
print(original_array)

# Remove NaN values using boolean indexing
array_without_nan = original_array[~np.isnan(original_array)]

# Print the array after removing NaN values
print("After removing nan values:")
print(array_without_nan)


Original array:
[200. 300.  nan  nan  nan 700.]
After removing nan values:
[200. 300. 700.]


Original array:
[200. 300.  nan  nan  nan 700.]
[ True  True False False False  True]
[200. 300. 700.]


7.Write a NumPy program to find indices of elements equal to zero in a NumPy array.
Sample Output:
Original array:
[1 0 2 0 3 0 4 5 6 7 8]
Indices of elements equal to zero of the said array:
[1 3 5]


In [1]:
import numpy as np

# Define the original array
original_array = np.array([1, 0, 2, 0, 3, 0, 4, 5, 6, 7, 8])

# Print the original array
print("Original array:")
print(original_array)

# Find indices of elements equal to zero
zero_indices = np.where(original_array == 0)[0]

#zero_indices = np.where(original_array == 0)[0]

# Print the indices of elements equal to zero
print("Indices of elements equal to zero of the said array:")
print(zero_indices)


Original array:
[1 0 2 0 3 0 4 5 6 7 8]
Indices of elements equal to zero of the said array:
[1 3 5]


8.Write a NumPy program to round elements of the array to the nearest integer, and then calculate the abslute value element wise.
Sample Output:
Original array:
[-0.7 -1.5 -1.7 0.3 1.5 1.8 2. ]
Round elements of the array to the nearest integer:
[1. 2. 2. 0. 2. 2. 2.]


In [2]:
import numpy as np

# Define the original array
original_array = np.array([-0.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.])

# Print the original array
print("Original array:")
print(original_array)

rounded_array = np.round(original_array)
print("Round elements of the array to the nearest integer:")
print(rounded_array)


absolute_array = np.abs(rounded_array)

print("Absolute value of elements in the rounded array:")

print(absolute_array)




Original array:
[-0.7 -1.5 -1.7  0.3  1.5  1.8  2. ]
Round elements of the array to the nearest integer:
[-1. -2. -2.  0.  2.  2.  2.]
Absolute value of elements in the rounded array:
[1. 2. 2. 0. 2. 2. 2.]


9.Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.
Sample output:
Original array:
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[ 0 0 2 2 2 -7 200]


In [4]:
arr1 =  np.array([1, 3, 5 ,7 ,0])


arr_diff = np.diff(arr1)

arr_diff = np.concatenate(([0,0], arr_diff))

arr_diff= np.append(arr_diff, [200] )


print("Difference between neighboring elements, element-wise, and prepend [0, 0] and append [200] to the said array:")
print(arr_diff)



Difference between neighboring elements, element-wise, and prepend [0, 0] and append [200] to the said array:
[  0   0   2   2   2  -7 200]


10.Write a NumPy program to get the indices of the sorted elements of a given array.
Expected Output:
Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]

In [6]:
import numpy as np

# Define the original array
original_array = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

# Print the original array
print("Original array:")
print(original_array)

# Get the indices of the sorted elements
sorted_indices = np.argsort(original_array)

# Print the sorted indices
print("Indices of the sorted elements of a given array:")
print(sorted_indices)





Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


11.Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).
Sample output:
Original array:
[ 70 50 20 30 -11 60 50 40]
After partitioning on 4 the position:
[-11 30 20 40 50 50 60 70]

In [ ]:
import numpy as np

# Define the original array
original_array = np.array([70, 50, 20, 30, -11, 60, 50, 40])

# Print the original array
print("Original array:")
print(original_array)

# Define the partition position
partition_position = 4

# Partition the array

np.random.shuffle(original_array)
partitioned_array = np.partition(original_array, partition_position)

# Print the partitioned array
print("After partitioning on the position:", partition_position)
print(partitioned_array)


12.Problem 12
Compute the euclidean distance between two arrays a and b.
Input:
[1,2,3,4,5]
[4,5,6,7,8]
Euclidean distance is: 6.7082

In [ ]:
import numpy as np

# Input arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

# Compute Euclidean distance
distance = np.linalg.norm(a - b)

print("Euclidean distance is:", round(distance, 4))


Problem 13
Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.
Input:
array([1, 3, 7, 1, 2, 6, 0, 1])
Desired Output:
array( [2, 5])
where, 2 and 5 are the positions of peak values 7 and 6.


In [ ]:
def find_peaks(array):
    peaks = []
    for i in range(1, len(array) - 1):
        if array[i] > array[i - 1] and array[i] > array[i + 1]:
            peaks.append(i)
    return np.array(peaks)

# Input array
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# Find peaks
peak_positions = find_peaks(a)

# Print result
print("Peak positions:", peak_positions)




Problem 14
Find the index of nth repetition of number i .
Inputs
array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5 (from user)
i = 1 (from user)
Output
8

In [9]:
def find_nth_repetition_index(array, n, i):
    indices = np.where(array == i)[0]  # Find indices where i appears
    if len(indices) < n:  # If number of occurrences is less than n
        return -1  # Return -1 indicating not found
    return indices[n - 1]  # Return the index of the nth occurrence

# Input array
arr = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
# i is one and and fith time one repeats on index 8
n = 5
i = 1

# Find nth repetition index
index = find_nth_repetition_index(arr, n, i)

# Print result
print("Index of nth repetition of number", i, "is:", index)



Index of nth repetition of number 1 is: 8


6.Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.
Sample Output:
50th percentile (median):
3.0
40th percentile:
2.6
90th percentile:
4.6


In [17]:
# Sample array
array = np.array([1, 2, 3, 4, 5])

# Calculate percentiles
percentile_50 = np.percentile(array, 50)
percentile_40 = np.percentile(array, 40)
percentile_90 = np.percentile(array, 90)

# Print percentiles
print("50th percentile (median):")
print(percentile_50)
print("40th percentile:")
print(percentile_40)
print("90th percentile:")
print(percentile_90)

50th percentile (median):
3.0
40th percentile:
2.6
90th percentile:
4.6
